fix(vou-42): combine items service
VOU-jcxdc/vou-be pull request #54
Opened 2024-08-26 15:43 UTC by ducviet5138

2024-08-27 01:53 UTC, Quan0308 requested changes
Task này đang là combine item service, đổi tên service và module luôn ấy, không là bị trùng với task item của Trúc

2024-08-27 01:53 UTC, Quan0308 commented on libs/database/src/schemas/combine_items.schema.ts
> +@Schema({
- define tên collection cho giống erd luôn
- add thêm property version key là false, đỡ phải handle trong helper

2024-08-27 01:53 UTC, Quan0308 commented on libs/database/src/mongo-database.module.ts
> +  exports: [MongooseModule],
Chưa biết sao phải export cái module này, module của lib mà

2024-08-28 02:10 UTC, Quan0308 commented on apps/item-service/src/modules/combine-item/combine_item.service.ts
> +      const data = await this.combineItemsModel.save(mappedDto);
Chỗ này trước khi tạo recipe thì kiểm tra trong event đó có bao nhiêu item đó mới tạo được chứ nhỉ. Giả sử event đó public có 20 item A, mà công thức là phải 25 item A mới được thì không có user nào ghép được

2024-08-28 02:19 UTC, Quan0308 commented on apps/main-api/src/modules/item/combine_item.controller.ts
> +}
T đang expect sẽ có api lấy các recipe liên quan tới item đó, api sẽ là "/items/:itemId/recipes". Kết quả sẽ trả ra các công thức liên quan tới item này, bao gồm cả là item này là thành phần của công thức hay các công thức để đổi được item này.

2024-08-28 02:28 UTC, Quan0308 commented on apps/item-service/src/modules/combine-item/combine_item.service.ts
> +      const mappedDto = dto as CombineItems;
Kiểm tra số lượng của các item có trong event rồi mới được tạo công thức ghép

2024-08-28 04:53 UTC, ducviet5138 commented on apps/main-api/src/modules/item/combine_item.controller.ts
> +}
ủa như có mà
![Uploading image.png…]()

2024-08-28 04:54 UTC, ducviet5138 commented on apps/main-api/src/modules/item/combine_item.controller.ts
> +}
này truyền nhiều items dô được, nếu mà đổi ở ngoài thì gọi cái này cho lẹ. Nó trả hết mấy vouchers/items có thể đổi được từ item mình truyền vào

2024-08-28 07:29 UTC, Quan0308 commented on apps/main-api/src/modules/item/combine_item.controller.ts
> +}
- Tại cái api path `items/:itemId/recipes` sẽ dễ hiểu hơn
- Cái hiện tại m để function là get mà method là post thấy dễ bị nhầm lắm

2024-08-28 13:00 UTC, Quan0308 requested changes

2024-08-28 13:00 UTC, Quan0308 commented on apps/item-service/src/modules/item/item.service.ts
> +        itemRecipe: { $elemMatch: { itemId: id } },
cần lấy thêm công thức mà item đó là target

2024-08-28 13:00 UTC, Quan0308 commented on apps/item-service/src/modules/combine-item/combine_item.service.ts
>  export class CombineItemService {
Lấy thêm thông tin của item đó từ bảng relationship

2024-08-29 01:58 UTC, Quan0308 approved these changes
LGTM

2024-08-29 01:58 UTC, merged